### ISSUE TITLE
VictoriaMetrics datasource

### ISSUE THREAD

**Issue by d00m178** [spectraphilic/grafana-windrose#18]
Is it possible to use this plugin with VictoriaMetrics?

**Comment by valyala** [comment]
Morw general question: to add support or an example query for [Prometheus datasource in Grafana](https://grafana.com/docs/grafana/latest/datasources/prometheus/). This datasource is compatible with VictoriaMetrics. See also [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html).

**Comment by newrushbolt** [comment]
In order to make this plugin work with any prometheus-compatible datasource(including VictoriaMetrics), you need to set 2 queries: one for wind speed and one for speed direction.
You also need to set "Legend" field to "direction" and "speed" to the corresponding queries.
The fragment of JSON-schema:
```json
"targets": [
    {
        "datasource": {
        "type": "prometheus",
        "uid": "P4169E866C3094E38"
        },
        "exemplar": false,
        "expr": "meteo_ws_mean{location=\"$location\"}",
        "instant": false,
        "interval": "",
        "legendFormat": "speed",
        "refId": "A"
    },
    {
        "datasource": {
        "type": "prometheus",
        "uid": "P4169E866C3094E38"
        },
        "exemplar": false,
        "expr": "meteo_wd_mean{location=\"$location\"}",
        "hide": false,
        "instant": false,
        "interval": "",
        "legendFormat": "direction",
        "refId": "B"
    }
]
```

Visual setup:
![image](https://user-images.githubusercontent.com/19495016/148591247-14b6725a-438e-47d8-a93f-94f2056b1056.png)

Result:
![image](https://user-images.githubusercontent.com/19495016/148591366-ff655b45-3035-4389-bc33-9fd52a6d5f1b.png)

Tested with following versions:
spectraphilic/grafana-windrose@c6b6d4f (Aug 13, 2021)
grafana/grafana@8.3.3 (Dec 14, 2021)
VictoriaMetrics/VictoriaMetrics@1.51.1 (Dec 27, 2020)

**Comment by d00m178** [comment]
confirm - it works)

**Comment by jdavid** [comment]
Thanks @newrushbolt , I've added a section to the README based on your comment, see https://github.com/spectraphilic/grafana-windrose#prometheus ; feel free to amend it with a PR if there's something wrong.

Closing.

**Comment by krlosg07** [comment]
I confirm too, it works with v9.0.6 and influxdb....
